### ISSUE TITLE
Webdriver Injection

### ISSUE THREAD

**Issue by MaheshGooner** [njunior1980/ExtentReportAmazon#1]
Hey,

Gone through your article on medium and it looks great and simple. But one issue with the webdriver instance not being global when you have more than one feature file. would you be able to fix it please ?

**Comment by njunior1980** [comment]
Hello Mahesh, thanks for your comment. But I didn't understand when I said about global webdriver. First it was a very simple example, I didn't go into the details and then we have in the Boostrapper.cs class a universal webdriver that can be used on any page object.

Where did you see the problem?

If you want to inject webdriver because it is 2 ways:

- use an ioc framework (singleton mode)
- create a class using facade pattern with your webdriver

Would it be this?

Thanks again!
